### ISSUE TITLE
Client console GUI app

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#12]
🔗 **Depends on:** [Implement base client abstractions in Rubberduck.Client](#)

A small standalone executable that will serve as a proof-of-concept for client/server RPC communications and lay the groundwork and produce abstractions usable for all RPC clients.

As a client, this application should either find or spawn the server process if it isn't already running: all Server.LocalDb clients should be connecting to the same server instance.

The application should present a tabbed UI with a "console" tab showing the server's trace log output, with commands to pause/resume tracing, set the server's trace level and other configuration settings. A status bar should display server info including name, version, uptime, number of connected clients, and the number of RPC messages sent and received.

A "database" tab should present metadata about each table, including the number of records, and the user should be able to double-click on a table or view item (or click a button) to bring up a data grid presenting/previewing the data, and commands to export the data to various formats, including CSV text files and Excel workbooks.

Aside from the LocalDb-specific tabs, the UI components will be mostly shared between the different client applications.

### Subtasks

- [ ] Finalize the shared "shell" UI components (xaml) of console client GUI apps
- [ ] Implement a `LocalDbClientService` class that communicates with the LocalDb RPC server
- [ ] Implement/honor console client configurations/options/capabilities
  - [ ] The console UI allows displaying different fonts/sizes/colors (and icons) depending on log level and property. For example the `Id` property might be configured to be displayed in a bold font, and the actual `Message` can be dark red for error-level items and the `VerboseMessage` could be shown in italics at the "info" level, but in monospace bright yellow at the "error" level.
- [ ] Implement the commands:
  - [ ] **Connect** to connect the client app to the LocalDb RPC server process (spawns it if it isn't running)
  - [ ] **Disconnect** to disconnect the client app from the LocalDb RPC server (process will exit if no connected clients remain)
  - [ ] **Exit** to cleanly disconnect the client app before terminating the client process; server remains alive if there are other clients.
  - [ ] **ClearConsole** to remove all messages in the console output; new messages may continue to be displayed.
  - [ ] **PauseTrace** to command the server to temporarily stop writing trace logs altogether, without disabling logging in the server configuration.
  - [ ] **ResumeTrace** to command the server to resume writing all trace logs when trace logging is paused.
  - [ ] **SaveServerSettings** to persist any changes to the server configuration.
  - [ ] **SaveClientSettings** to persist any changes to the client configuration.
  - [ ] **RefreshServerInfo** to request updated server state; this command should be executed with a configurable timer that shouldn't tick more often than once per second. The server uptime can be used to synchronize a local `TimeSpan` value that represents the estimated server uptime and that can be updated locally between the requests.
