### ISSUE TITLE
[EPIC] Shell UI

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#75]
UI work to do around the Rubberduck Editor main window, at a high level.

- [x] Initializes LSP server
- [ ] Selectable/dynamic theming (JSON)
  - [ ] Light/blue theme
  - [ ] Dark theme
  - [ ] Dark/blue theme
  - [ ] Can be customized
  - [ ] Includes syntax highlighting colors
- [x] Docking panels (side, bottom)
  - [x] Can be hidden/collapsed
  - [x] Can be expanded
  - [x] Can be pinned to remain expanded
- [ ] Document/editor tabs
  - [ ] Can be pinned (tab header)
  - [ ] Can be closed
  - [ ] Sends open/closed LSP notifications 
- [ ] Status bar UI
  - [ ] Initial: Shows server connection status
  - [ ] Any doc: Shows document/selection info
  - [ ] Source: Shows diagnostics ("n issues")
- [x] Menu bar UI
- [ ] Floating/undocked windows
  - [ ] Can be re-docked
  - [ ] Can accept/dock other document tabs
- [x] Base toolwindow UI ("ThunderFrame")
- [ ] Text document template
- [ ] Markdown document template
  - [ ] Shows a preview pane
- [ ] JSON document template
- [ ] Source file document template
- [x] MessageBox dialog +service
  - [x] ShowMessage/ShowMessageRequest LSP handlers
  - [x] Can render markdown
  - [x] Can be ignored ("do not show again")
  - [x] Can be expanded to show additional markdown content
  - [ ] Looks good (needs a larger font and a large SVG icon, at least)
- [x] New Project dialog
  - [x] Shows VBA projects from VBE add-in
  - [x] Hides projects drop-down when running without the VBE add-in
  - [x] Can create a project from a template
  - [x] Creates workspace folders
  - [x] Opens the created project
- [ ] Workspace Explorer toolwindow
  - [x] Represents workspaces in a tree view
  - [x] Toolbar shortcuts to create new project/workspace, open existing
  - [x] Open file command
  - [ ] Folder icons change on expand
  - [ ] Can be shown (empty) on startup
  - [ ] Can rename files/folders
   - [ ] Sends LSP notifications
  - [ ] Can create files/folders
    - [ ] Sends LSP notifications
  - [ ] Can delete files/folders
    - [ ] Sends LSP notifications
  - [ ] Can move (drag/drop) files/folders
    - [ ] Sends LSP notifications
  - [ ] Can drop files/folders from Windows Explorer
- [x] Settings dialog
  - [x] Boolean settings template
  - [x] String setting template
  - [x] Numeric setting template
  - [x] TimeSpan setting template
  - [x] Enum setting template (per enum)
  - [x] List setting template
    - [ ] can remove items from UI
  - [ ] Merge and serialize settings, defaults
  - [ ] Saves to disk on change
- [ ] Language Server Trace toolwindow
  - [x] Can be paused
  - [x] Can select verbosity
    - [ ] Affects corresponding settings
  - [ ] Command to open log file
  - [ ] Shows LSP LogTrace messages
