### ISSUE TITLE
[EPIC] Language Server

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#76]
Phase I

- [x] Initialize with a client
- [ ] Receive file contents in LSP handlers
- [ ] Load project references 
- [ ] Parse all project files
  - [ ] Send WorkdoneProgressStart and notify client of ongoing progress
  - [ ] Prioritize opened files
  - [ ] Send client folding ranges as soon as parse trees are available

Phase II
  - [ ] Send client semantic highlighting for the active document tab first, open documents second, all others last
  - [ ] Send client diagnostics with the same prioritization
- [ ] Implement server-side rename refactoring
  - [ ] Send client PreviewRename notification
- [ ] Implement server-side "formatting"
  - [ ] Indenter settings

Phase III
- [ ] Handle parameter info requests
- [ ] Handle completion list requests
