### ISSUE TITLE
[EPIC] Update Server 

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck3#77]
- [x] Runs a JsonRPC server
- [ ] Checks for updates on startup
- [ ] Can update itself
 - [ ] Checks for updates before updating RD3
- [ ] Can download RD3 release assets
- [ ] Can update RD3 language server
- [ ] Can update RD3 add-in client
- [ ] Can update RD3 editor
- [ ] Can detect RD3 running processes
